[deps]
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReachabilityBase = "379f33d0-9447-4353-bd03-d664070e549f"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
DisplayAs = "0.1"
Documenter = "1"
DocumenterCitations = "1.3"
ExponentialUtilities = "1"
IntervalArithmetic = "1"
JLD2 = "0.4 - 0.6"
LaTeXStrings = "1"
LazySets = "6"
Literate = "2"
MathematicalSystems = "0.14.1"
Optim = "0.15 - 0.22, 1, 2"
OrdinaryDiffEq = "6"
Plots = "1"
ReachabilityBase = "0.2.3 - 0.3"
Symbolics = "5 - 7"
